//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.04 at 03:07:53 PM NZST 
//


package rabbit.data.internal.xml.schema.events;

import java.sql.Timestamp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.joda.time.format.DateTimeFormat;


/**
 * <p>Java class for commandEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="commandEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{}countEventType">
 *       &lt;attribute name="commandId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commandEventType")
public class CommandEventType
    extends CountEventType
{

    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected String sid;
    @XmlAttribute(required = true)
    protected String category;
    @XmlAttribute(required = true)
    protected String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@XmlAttribute(required = true)
    protected String tsStart;
    @XmlAttribute(required = true)
    protected String tsEnd;
    
  //  @XmlAttribute(required = true)
   // protected String ts = timestampAsString(ts1);
    


    public String getTimeStamp() {
		return tsStart;
	}

	public void setTimeStamp(String tsStart) {
		this.tsStart = tsStart;
		this.tsEnd = tsStart;
	}

	/**
     * Gets the value of the commandId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandId() {
        return id;
    }

    /**
     * Sets the value of the commandId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandId(String value) {
        this.id = value;
    }

    public String getSid() {
		return sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}
   

}
